/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as integration from "./integration";
export type { integration };
import type * as registry from "./registry";
export type { registry };
import type * as voteContract from "./voteContract";
export type { voteContract };
