/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RegisterVoteContract } from "./RegisterVoteContract";
export type { VoteAndImplementContract } from "./VoteAndImplementContract";
export type { VoteContract } from "./VoteContract";
export type { VoteContractPrimitive } from "./VoteContractPrimitive";
export type { VotingStatusHandling } from "./VotingStatusHandling";
