/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  RevertFunction,
  RevertFunctionInterface,
} from "../../../../contracts/test/Revert.sol/RevertFunction";

const _abi = [
  {
    inputs: [],
    name: "fail",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610156806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063a9cc471814610030575b600080fd5b61003861003a565b005b600061007b576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610072906100a0565b60405180910390fd5b565b600061008a602c836100c0565b9150610095826100d1565b604082019050919050565b600060208201905081810360008301526100b98161007d565b9050919050565b600082825260208201905092915050565b7f596f75206661696c65642c206576656e206d6f7265206d6973657261626c792060008201527f7468616e206265666f726521000000000000000000000000000000000000000060208201525056fea264697066735822122031798d36b5cb415d4cc9dac14e7c01b4bed9f732d1eac94ebb102a53e01dc88464736f6c63430008040033";

type RevertFunctionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RevertFunctionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RevertFunction__factory extends ContractFactory {
  constructor(...args: RevertFunctionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<RevertFunction> {
    return super.deploy(overrides || {}) as Promise<RevertFunction>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): RevertFunction {
    return super.attach(address) as RevertFunction;
  }
  override connect(signer: Signer): RevertFunction__factory {
    return super.connect(signer) as RevertFunction__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RevertFunctionInterface {
    return new utils.Interface(_abi) as RevertFunctionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RevertFunction {
    return new Contract(address, _abi, signerOrProvider) as RevertFunction;
  }
}
