/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVoteAndImplementContract } from "./IVoteAndImplementContract";
export type { IVoteContract } from "./IVoteContract";
