/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iVoteContractSol from "./IVoteContract.sol";
export type { iVoteContractSol };
import type * as voteContractSol from "./VoteContract.sol";
export type { voteContractSol };
