/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dummyErc20Sol from "./DummyERC20.sol";
export type { dummyErc20Sol };
import type * as revertSol from "./Revert.sol";
export type { revertSol };
export type { DummyIntegrator } from "./DummyIntegrator";
