/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CanVote } from "./CanVote";
export type { CanVotePrimitive } from "./CanVotePrimitive";
export type { CanVoteWithoutStarting } from "./CanVoteWithoutStarting";
