/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGetCurrentIndex,
  IGetCurrentIndexInterface,
} from "../../../../contracts/voting/IVoting.sol/IGetCurrentIndex";

const _abi = [
  {
    inputs: [],
    name: "getCurrentIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGetCurrentIndex__factory {
  static readonly abi = _abi;
  static createInterface(): IGetCurrentIndexInterface {
    return new utils.Interface(_abi) as IGetCurrentIndexInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGetCurrentIndex {
    return new Contract(address, _abi, signerOrProvider) as IGetCurrentIndex;
  }
}
