/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGetCurrentIndex__factory } from "./IGetCurrentIndex__factory";
export { IVoting__factory } from "./IVoting__factory";
