/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VotingStatusHandling,
  VotingStatusHandlingInterface,
} from "../../../../../contracts/registration/voteContract/VoteContract.sol/VotingStatusHandling";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "voteIndex",
        type: "uint256",
      },
    ],
    name: "getCurrentVotingStatus",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class VotingStatusHandling__factory {
  static readonly abi = _abi;
  static createInterface(): VotingStatusHandlingInterface {
    return new utils.Interface(_abi) as VotingStatusHandlingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VotingStatusHandling {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as VotingStatusHandling;
  }
}
