/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DummyERC20__factory } from "./DummyERC20__factory";
export { IDummyERC20__factory } from "./IDummyERC20__factory";
