/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as canVoteSol from "./CanVote.sol";
export { CanVoteAndDelegateImplement__factory } from "./CanVoteAndDelegateImplement__factory";
export { CanVoteAndImplement__factory } from "./CanVoteAndImplement__factory";
