/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as votingRegistrySol from "./VotingRegistry.sol";
export type { votingRegistrySol };
export type { IVotingRegistry } from "./IVotingRegistry";
