/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as integration from "./integration";
export * as registry from "./registry";
export * as voteContract from "./voteContract";
