/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVoteAndImplementContract__factory } from "./IVoteAndImplementContract__factory";
export { IVoteContract__factory } from "./IVoteContract__factory";
