/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as integration from "./integration";
export * as registry from "./registry";
export * as samples from "./samples";
export * as test from "./test";
export * as voteContract from "./voteContract";
export * as voting from "./voting";
