/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleMajorityVote } from "./SimpleMajorityVote";
export type { SimpleMajorityVoteAndImplement } from "./SimpleMajorityVoteAndImplement";
export type { ThresholdTokenVote } from "./ThresholdTokenVote";
export type { ThresholdTokenVoteAndImplement } from "./ThresholdTokenVoteAndImplement";
