/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RevertConstructor } from "./RevertConstructor";
export type { RevertFunction } from "./RevertFunction";
