/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as canVoteSol from "./CanVote.sol";
export type { canVoteSol };
export type { CanVoteAndDelegateImplement } from "./CanVoteAndDelegateImplement";
export type { CanVoteAndImplement } from "./CanVoteAndImplement";
