/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CategoryRegistration } from "./CategoryRegistration";
export type { Registry } from "./Registry";
export type { VotingContractRegistration } from "./VotingContractRegistration";
