/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CategoryRegistration__factory } from "./CategoryRegistration__factory";
export { Registry__factory } from "./Registry__factory";
export { VotingContractRegistration__factory } from "./VotingContractRegistration__factory";
