/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CanVotePrimitive,
  CanVotePrimitiveInterface,
} from "../../../../contracts/integration/CanVote.sol/CanVotePrimitive";

const _abi = [
  {
    inputs: [],
    name: "getTotalVotesStarted",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "voteIndex",
        type: "uint256",
      },
    ],
    name: "getVoteInfo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CanVotePrimitive__factory {
  static readonly abi = _abi;
  static createInterface(): CanVotePrimitiveInterface {
    return new utils.Interface(_abi) as CanVotePrimitiveInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CanVotePrimitive {
    return new Contract(address, _abi, signerOrProvider) as CanVotePrimitive;
  }
}
