/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iVoteContractSol from "./IVoteContract.sol";
export * as voteContractSol from "./VoteContract.sol";
