/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface CanVotePrimitiveInterface extends utils.Interface {
  functions: {
    "getTotalVotesStarted()": FunctionFragment;
    "getVoteInfo(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getTotalVotesStarted" | "getVoteInfo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getTotalVotesStarted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteInfo",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTotalVotesStarted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteInfo",
    data: BytesLike
  ): Result;

  events: {};
}

export interface CanVotePrimitive extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CanVotePrimitiveInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getTotalVotesStarted(overrides?: CallOverrides): Promise<[BigNumber]>;

    getVoteInfo(
      voteIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;
  };

  getTotalVotesStarted(overrides?: CallOverrides): Promise<BigNumber>;

  getVoteInfo(
    voteIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber]>;

  callStatic: {
    getTotalVotesStarted(overrides?: CallOverrides): Promise<BigNumber>;

    getVoteInfo(
      voteIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    getTotalVotesStarted(overrides?: CallOverrides): Promise<BigNumber>;

    getVoteInfo(
      voteIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getTotalVotesStarted(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVoteInfo(
      voteIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
